name: morning
on:
  schedule:
  - cron:  '0 23 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
#     - run: pip install -r ./requirements.txt && python ./main.py
    
    - name: Commit and push if changed   # 将文件更新到仓库
      run: |
        echo $(date +%F%n%T) >> log.log
        git diff
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        git commit -m "Keep Actions"
        git push

#     env:
#       APP_ID: ${{ secrets.APP_ID }}
#       APP_SECRET: ${{ secrets.APP_SECRET }}
#       TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
#       USER_ID: ${{ secrets.USER_ID }}
#       START_DATE: ${{ secrets.START_DATE }}
#       BIRTHDAY_GRIL: ${{ secrets.BIRTHDAY_GRIL }}
#       CITY: ${{ secrets.CITY }}
